# Generated by Django 5.2.8 on 2025-12-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
